---
name: quran_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.13.1
  introduction_screen: ^3.1.8
  go_router: ^8.0.5
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.4.0
  quran: ^1.2.2
  avatar_glow: ^2.0.2
  flutter_zoom_drawer: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Quran logo.png
  min_sdk_android: 21
  windows:
    generate: true
    image_path: assets/images/Quran logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/Quran logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
  - family: Amiri
    fonts:
    - asset: assets/Fonts/Amiri-Regular.ttf