---
name: quran_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  introduction_screen: ^3.1.12
  go_router: ^13.0.0
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.6.0
  quran: ^1.2.3
  avatar_glow: ^2.0.2
  flutter_zoom_drawer: any
  flutter_img: ^0.1.5+111
  scrollable_positioned_list: ^0.3.8
  awesome_dialog: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sidebarx: ^0.16.3
  flutter_bloc: ^8.1.3

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Quran logo.png
  min_sdk_android: 21
  windows:
    generate: true
    image_path: assets/images/Quran logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/Quran logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/Fonts/Amiri-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Black.ttf
    - family: Noto Kufi Arabic
      fonts:
        - asset: assets/Fonts/NotoKufiArabic-VariableFont_wght.ttf
