import 'package:flutter/material.dart';

Color blueColor = const Color(0xffA8DCD9);
Color pinkColor = const Color(0xffFE5D9F);
Color blueAccentColor = Colors.blueAccent;
Color brownColorShade100 = Colors.brown.shade100;
Color darkBrown = const Color(0xff721121);
Color lightBrown = const Color(0xffA5402D);
Color offWhite = const Color(0xffFFC07F);
Color earthYellow = const Color(0xffEEB868);
Color chamoisee = const Color(0xffA47963);
Color brown = const Color(0xff823200);
Color papayaWhip = const Color(0xffFFEFD3);
Color jasmine = const Color(0xffFCD581);
Color ivonyWhite = const Color(0xffFFFFF2);
Color spaceCadit = const Color(0xff192A51);
Color lavenderBlush = const Color(0xffF5E6E8);
Color slightOffWhite = const Color(0xffffcf9f);
Color fawn = const Color(0xffE6AA68);
Color zaffre = const Color(0xff3626A7);
Color officeGreen = const Color(0xff157F1F);